# Generated by Django 3.0 on 2020-03-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=225)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('subtotal', models.IntegerField()),
            ],
        ),
    ]
